version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Debug working directory
          command: |
            echo "PWD = $(pwd)"
            echo "Contents:"
            ls -la
      - run:
          name: Run tests
          command: pytest test_units.py

workflows:
  version: 2
  build:
    jobs:
      - build
